export * from "./accomplishments/accomplishments";
export * from "./contact/contact";
export * from "./education/education";
export * from "./history/history";
export * from "./introduction/introduction";
export * from "./languages/languages";
export * from "./publications/publications";
export * from "./reasons/reasons";
export * from "./testimonials/testimonials";
export * from "./skills/skills";
export * from "./toc/toc";
export * from "./travel/travel";
// export * from "./accomplishments/accomplishments";
// export * from "./citizenship/citizenship";
